name: Mineceit
main: mineceit\MineceitCore
version: 1.0.0
api: "3.0.0"
author: jkorn
description: "The core for the server Mineceit."
website: "https://github.com/jkorn2324"
depend:
  - "FormAPI"

permissions:
  mineceit.permission.duel:
    description: 'Permission to use /duel command.'
    default: true
  mineceit.permission.hub:
    description: 'Permission to use /hub command.'
    default: true
  mineceit.permission.stats:
    description: 'Permission to use /stats command.'
    default: true
  mineceit.permission.spec:
    description: 'Permission to use /spec command.'
    default: true
  mineceit.permission.settings:
    description: 'Permission to use /settings command.'
    default: true
  mineceit.permission.shop:
    description: 'Permission to use /shop command.'
    default: true
  mineceit.cosmetic.shop:
    description: 'Permission to use /cosmetic command.'
    default: true
  mineceit.permission.auction:
    description: 'Permission to use /auction command.'
    default: true    



